name: Generate Pacman Contribution Graph

on:
  # Jalankan setiap 12 jam (pada tengah malam dan siang hari UTC)
  schedule:
    - cron: "0 */12 * * *"
  # Izinkan untuk menjalankan action ini secara manual dari tab Actions
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Langkah 1: Generate file SVG.
      # File ini akan dibuat di root workspace dengan nama pacman-contribution-graph.svg
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # Langkah 2: Buat folder 'dist' dan pindahkan file SVG ke dalamnya.
      # INI ADALAH LANGKAH PENTING YANG HILANG.
      - name: Move generated file to dist directory
        run: |
          mkdir -p dist
          mv pacman-contribution-graph.svg dist/

      # Langkah 3: Push isi dari folder 'dist' ke branch 'output'.
      # Action ini sekarang akan menemukan file SVG di dalam 'dist'.
      - name: Push contribution graph to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # Branch tujuan untuk menyimpan file SVG
          target_branch: output
          # Direktori yang berisi file yang akan di-push
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}