# Beri nama yang jelas, karena file ini sekarang melakukan dua hal
name: Generate Contribution Graphics

on:
  # Jalankan setiap 12 jam
  schedule:
    - cron: "0 */12 * * *"
  # Izinkan untuk menjalankan action ini secara manual
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Tambah waktu jaga-jaga

    steps:
      # Langkah 1: Generate file Pac-Man
      # Hasilnya: pacman-contribution-graph.svg
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # Langkah 2: Generate file Snake
      # Menggunakan action Platane/snk yang populer untuk ini
      # Hasilnya: github-contribution-grid-snake.svg
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # Kita akan membuat outputnya menjadi file bernama "snake.svg" agar konsisten
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # Langkah 3: Pindahkan file Pac-Man ke folder 'dist'
      # Ini agar kedua file berada di lokasi yang sama sebelum di-push
      - name: Move pacman graph to dist directory
        run: |
          # Pindahkan pacman ke dist. File snake sudah ada di dist dari langkah sebelumnya.
          mv pacman-contribution-graph.svg dist/

      # Langkah 4: Push SEMUA isi dari folder 'dist' ke branch 'output'
      # Sekarang 'dist' berisi 'pacman-contribution-graph.svg' DAN 'snake.svg'
      - name: Push all graphics to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}